services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: tu_clave_secreta_segura
